/** Semantic design tokens — always read CSS variables (theme-aware). */
export const V = {
  bg: "var(--bg)",
  paper: "var(--paper)",
  panel: "var(--panel)",
  card: "var(--card)",
  line: "var(--line)",
  line2: "var(--line2)",
  ink: "var(--ink)",
  muted: "var(--muted)",
  faint: "var(--faint)",
  accent: "var(--accent)",
  accentInk: "var(--accent-ink)",
  accentWeak: "var(--accent-weak)",
  danger: "var(--danger)",
  success: "var(--success)",
  warn: "var(--warn)",
  warnBg: "var(--warn-bg)",
  illiquidBar: "var(--illiquid-bar)",
  cardBorder: "var(--card-border)",
  cardBorderW: "var(--card-border-w)",
  rowBorderW: "var(--row-border-w)",
  shadow: "var(--shadow)",
  shadowActive: "var(--shadow-active)",
  radius: "var(--radius)",
  radiusSm: "var(--radius-sm)",
  radiusBtn: "var(--radius-btn)",
  fontDisplay: "var(--font-display)",
  fontMono: "var(--font-mono)",
  navBg: "var(--nav-bg)",
  alertBg: "var(--alert-bg)",
  alertBorder: "var(--alert-border)",
  alertShadow: "var(--alert-shadow)",
  calloutBg: "var(--callout-bg)",
  calloutShadow: "var(--callout-shadow)",
  inputBg: "var(--input-bg)",
  hotBg: "var(--hot-bg)",
  hotBorder: "var(--hot-border)",
} as const;

/** @deprecated use V — kept for gradual migration */
export const C = {
  ...V,
  app: V.bg,
  sub: V.muted,
  debt: V.danger,
  up: V.success,
  blue: V.accent,
  down: V.danger,
  amber: V.warn,
  sans: V.fontDisplay,
  mono: V.fontMono,
  accentWeak: V.accentWeak,
  warnBg: V.warnBg,
  illiquidBar: V.illiquidBar,
};
